package view.Contains;

import java.util.ArrayList;
import java.util.List;
import model.DienThoai;
import model.HoaDonChiTiet;
import model.KhachHang;

public class jplDonHang extends javax.swing.JPanel {

    // list Lưu danh sách sản phẩm mà khách chọn
    private List<DienThoai> list;
    // lưu khách hàng
    private KhachHang kh;
    private List<HoaDonChiTiet> hoaDonChiTiets;

    public jplDonHang(int donSo) {
        initComponents();
        this.setName("Đơn" + donSo);
        hoaDonChiTiets  = new ArrayList<>();
    }

    public List<HoaDonChiTiet> getHoaDonChiTiets() {
        return hoaDonChiTiets;
    }

    public void setHoaDonChiTiets(List<HoaDonChiTiet> hoaDonChiTiets) {
        this.hoaDonChiTiets = hoaDonChiTiets;
    }
    
    public List<DienThoai> getList() {
        return list;
    }

    public void setList(List<DienThoai> list) {
        this.list = list;
    }

    public KhachHang getKh() {
        return kh;
    }

    public void setKh(KhachHang kh) {
        this.kh = kh;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbHoaDonChiTiet = new javax.swing.JTable();

        tbHoaDonChiTiet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbHoaDonChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbHoaDonChiTiet);
        if (tbHoaDonChiTiet.getColumnModel().getColumnCount() > 0) {
            tbHoaDonChiTiet.getColumnModel().getColumn(0).setMinWidth(30);
            tbHoaDonChiTiet.getColumnModel().getColumn(0).setPreferredWidth(30);
            tbHoaDonChiTiet.getColumnModel().getColumn(0).setMaxWidth(30);
            tbHoaDonChiTiet.getColumnModel().getColumn(2).setMinWidth(70);
            tbHoaDonChiTiet.getColumnModel().getColumn(2).setPreferredWidth(70);
            tbHoaDonChiTiet.getColumnModel().getColumn(2).setMaxWidth(70);
            tbHoaDonChiTiet.getColumnModel().getColumn(3).setMinWidth(120);
            tbHoaDonChiTiet.getColumnModel().getColumn(3).setPreferredWidth(120);
            tbHoaDonChiTiet.getColumnModel().getColumn(4).setMinWidth(120);
            tbHoaDonChiTiet.getColumnModel().getColumn(4).setPreferredWidth(120);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbHoaDonChiTiet;
    // End of variables declaration//GEN-END:variables
}
